psmar16-elasticsearch:
  container_name: psmar16-elasticsearch
  image: elasticsearch:1.7.3
  # volumes:
  #   - ~/volumes/jhipster/psmar16/elasticsearch/:/usr/share/elasticsearch/data/
  ports:
    - "9200:9200"
    - "9300:9300"
psmar16-postgresql:
  container_name: psmar16-postgresql
  image: postgres:9.4.5
  # volumes:
  #   - ~/volumes/jhipster/psmar16/postgresql/:/var/lib/postgresql/
  environment:
    - POSTGRES_USER=psmar16
    - POSTGRES_PASSWORD=
  ports:
    - "5432:5432"
